// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP-8Eg21QKiA2e0pbmEfIvTkzjzx6IYM8',
    appId: '1:514965984109:web:00ce9ba9fb5274d1134064',
    messagingSenderId: '514965984109',
    projectId: 'flutter-absensi-780b5',
    authDomain: 'flutter-absensi-780b5.firebaseapp.com',
    storageBucket: 'flutter-absensi-780b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcB2D3E3oelnkF1fVxrS7srwl0GgwWBkg',
    appId: '1:514965984109:android:54bd20845f821bfe134064',
    messagingSenderId: '514965984109',
    projectId: 'flutter-absensi-780b5',
    storageBucket: 'flutter-absensi-780b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWSg43YytDS6g94DMoJLNzc_4S7DsdDU',
    appId: '1:514965984109:ios:5e1b1b350a885d07134064',
    messagingSenderId: '514965984109',
    projectId: 'flutter-absensi-780b5',
    storageBucket: 'flutter-absensi-780b5.appspot.com',
    iosBundleId: 'com.example.flutterAbsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWSg43YytDS6g94DMoJLNzc_4S7DsdDU',
    appId: '1:514965984109:ios:5e1b1b350a885d07134064',
    messagingSenderId: '514965984109',
    projectId: 'flutter-absensi-780b5',
    storageBucket: 'flutter-absensi-780b5.appspot.com',
    iosBundleId: 'com.example.flutterAbsensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP-8Eg21QKiA2e0pbmEfIvTkzjzx6IYM8',
    appId: '1:514965984109:web:5068c017d7518403134064',
    messagingSenderId: '514965984109',
    projectId: 'flutter-absensi-780b5',
    authDomain: 'flutter-absensi-780b5.firebaseapp.com',
    storageBucket: 'flutter-absensi-780b5.appspot.com',
  );
}
